version: 2.1
orbs:
  node: circleci/node@4.0.0
  heroku: circleci/heroku@1.2.2

jobs:
  test:
    executor: node/default

    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          command: yarn lint
          name: Eslint
      - run:
          command: yarn test:ci --maxWorkers=2
          name: Test
      - run:
          command: yarn coveralls
          name: Upload coverage report to Coveralls

  deploy_to_heroku:
    executor: heroku/default

    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  version: 2

  test-only:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - develop
                - master

  test-and-deploy:
    jobs:
      - test:
          filters:
              branches:
                only:
                  - master
      - deploy_to_heroku:
          requires:
            - test
